name: Tag versioning

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  
jobs:
  versioning:
    name: "Versioning"
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Install Dependencies
        run: npm install

      - name: Create version
        run: npm run docusaurus docs:version ${{ steps.get_version.outputs.VERSION }}

      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "releases/"
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "kind:release"
          pr_title: "[release] ${{ steps.get_version.outputs.VERSION }}"
