name: Tag versioning

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  
jobs:
  versioning:
    name: "Versioning"
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2

      - name: Get the tag
        id: get-tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Install Dependencies
        run: npm install

      - name: Create version
        run: npm run docusaurus docs:version ${{ steps.get-tag.outputs.TAG }}

      - name: Push release code
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b releases/${{ steps.get-tag.outputs.TAG }}
          git add -A
          git commit -m "Create version ${{ steps.get-tag.outputs.TAG }}"
          git push

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "master"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "kind:release"
          pr_title: "[release] ${{ steps.get-tag.outputs.TAG }}"
