name: Fetch references

on:
  push:
    branches: [master]
  
jobs:
  sdk:
    name: "SDK Refs"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          persist-credentials: false
          fetch-depth: 0 

      - name: Install asciidoctor
        run: sudo apt-get install asciidoctor

      - name: Install pandoc
        run: sudo apt-get install pandoc

      - name: Convert documents
        run: sh "$GITHUB_WORKSPACE/.github/workflows/tools/convert-asciidoc.sh" "$GITHUB_WORKSPACE/raw-refs/sdk/docs"

      - name: Move references
        run: mv "$GITHUB_WORKSPACE/raw-refs/sdk/docs" "$GITHUB_WORKSPACE/docs/references/sdk"
        
      - name: Commit files
        run: |
          git add "$GITHUB_WORKSPACE/docs/sdk"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update SDK references at $(git rev-parse HEAD)" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
